// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARPXuqC_ndgk-Hr76O6C8nPxT6gzBBoS8',
    appId: '1:64908334976:web:00a2ff7c2b05ba5a99d365',
    messagingSenderId: '64908334976',
    projectId: 'orbit-47bed',
    authDomain: 'orbit-47bed.firebaseapp.com',
    storageBucket: 'orbit-47bed.firebasestorage.app',
    measurementId: 'G-5HPRTNELVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0qO6E1c690NXuuKizjS0ia5k20Qq_2fQ',
    appId: '1:64908334976:android:379bdb970220fe8399d365',
    messagingSenderId: '64908334976',
    projectId: 'orbit-47bed',
    storageBucket: 'orbit-47bed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPpolWDiQxvYIOoYfznMr22JyMO3u5LaA',
    appId: '1:64908334976:ios:daa8b1ed602631b399d365',
    messagingSenderId: '64908334976',
    projectId: 'orbit-47bed',
    storageBucket: 'orbit-47bed.firebasestorage.app',
    androidClientId: '64908334976-mnbqpc9rbcjvd4un4s450btjd97m9ke9.apps.googleusercontent.com',
    iosClientId: '64908334976-v5tlv7vmnokc4hvnr1ka9dbv3c99qku6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPpolWDiQxvYIOoYfznMr22JyMO3u5LaA',
    appId: '1:64908334976:ios:daa8b1ed602631b399d365',
    messagingSenderId: '64908334976',
    projectId: 'orbit-47bed',
    storageBucket: 'orbit-47bed.firebasestorage.app',
    androidClientId: '64908334976-mnbqpc9rbcjvd4un4s450btjd97m9ke9.apps.googleusercontent.com',
    iosClientId: '64908334976-v5tlv7vmnokc4hvnr1ka9dbv3c99qku6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARPXuqC_ndgk-Hr76O6C8nPxT6gzBBoS8',
    appId: '1:64908334976:web:54c62c882753687099d365',
    messagingSenderId: '64908334976',
    projectId: 'orbit-47bed',
    authDomain: 'orbit-47bed.firebaseapp.com',
    storageBucket: 'orbit-47bed.firebasestorage.app',
    measurementId: 'G-WC19E11237',
  );

}